In [18]:
import pandas as pd
df = pd.read_csv('./안쓰는것들/trip_info_crawl.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df['cate_mix'] = df['요리'].str.replace(" ", "")
df['cate_mix'] = df['cate_mix'].str.replace(',',' ')
df.cate_mix.fillna('생략', inplace=True)

In [19]:
title_name = df.장소이름.unique()
title_name

array(['인디언키친', '명진전복', '우진해장국', ..., '주르레식당',
       '빠레뜨 한남 제주협재점', 'Seppy Bagel'], dtype=object)

In [20]:
arr = pd.DataFrame()
for i in title_name:
    arr = arr.append({'title':i,
                     'review_count':len(review_df[review_df['title'] == i]),
                     'review_mean':review_df[review_df['title'] == i].review_rate.mean()},
                     ignore_index=True)
arr

                           title  review_count  review_mean
0                          인디언키친          70.0     4.757143
1                           명진전복          90.0     3.911111
2                          우진해장국          90.0     4.044444
3                           올래국수          90.0     3.911111
4                          마초 그릴          64.0     4.562500
...                          ...           ...          ...
1589                     홍요깃거리카페           0.0          NaN
1590                        갈치공장           0.0          NaN
1591                       주르레식당           0.0          NaN
1592  빠레뜨 한남 제주협재점           0.0          NaN
1593                 Seppy Bagel           0.0          NaN

[1594 rows x 3 columns]

In [21]:
df = pd.merge(df, arr, how='outer', left_on='장소이름', right_on='title')
df.drop('title', axis=1, inplace=True)
df['review_mean'].fillna(0, inplace=True)
df

,장소이름,소개,가격대,요리,특별식 제공,식사 시간,특징,cate_mix,review_count,review_mean
0,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143
1,명진전복,NaN,NaN,"해산물, 아시아 요리, 한국",NaN,"점심식사, 저녁식사","좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, 주류 판매, 신용카드 결제 가...",해산물 아시아요리 한국,90.0,3.911111
2,우진해장국,NaN,NaN,"아시아 요리, 한국, 수프",NaN,"아침식사, 점심식사, 저녁식사","테이크아웃, 좌석, 주류 판매, 신용카드 결제 가능, 테이블 서비스",아시아요리 한국 수프,90.0,4.044444
3,올래국수,NaN,NaN,"아시아 요리, 한국",NaN,"점심식사, 저녁식사","좌석, 신용카드 결제 가능, 테이블 서비스",아시아요리 한국,90.0,3.911111
4,마초 그릴,NaN,"₩6,500 - ₩25,000","멕시코 요리, 사우스웨스턴, 라틴, 중앙아메리카",채식주의 식단,"점심식사, 저녁식사","테이크아웃, 좌석, 주류 판매, 무료 와이파이, 테이블 서비스, 텔레비전, 다양한 ...",멕시코요리 사우스웨스턴 라틴 중앙아메리카,64.0,4.562500
...,...,...,...,...,...,...,...,...,...,...
1688,홍요깃거리카페,NaN,NaN,"아시아 요리, 한국",NaN,NaN,NaN,아시아요리 한국,0.0,0.000000
1689,갈치공장,NaN,"₩12,000 - ₩30,000","해산물, 아시아 요리, 한국",NaN,NaN,NaN,해산물 아시아요리 한국,0.0,0.000000
1690,주르레식당,NaN,NaN,"아시아 요리, 한국, 컨템퍼러리, 퓨전",NaN,NaN,NaN,아시아요리 한국 컨템퍼러리 퓨전,0.0,0.000000
1691,빠레뜨 한남 제주협재점,NaN,NaN,NaN,NaN,"점심식사, 저녁식사",NaN,생략,0.0,0.000000
1692,Seppy Bagel,NaN,NaN,미국 요리,NaN,NaN,NaN,미국요리,0.0,0.000000

In [26]:
total = pd.merge(df, review_df, left_on='장소이름', right_on='title', how='outer').drop('title', axis=1)
total['review_text'].fillna('',inplace=True)
total

,장소이름,소개,가격대,요리,특별식 제공,식사 시간,특징,cate_mix,review_count,review_mean,region,review_date,review_id,review_rate,review_text
0,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143,제주,리뷰 게시 날짜: 3주 전,Go784818,1.0,전에 여기 너무 좋다고 리뷰 올렸고 그래서 친구 부부와 같이 다시 찾았습니다. 저희...
1,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143,제주,2021년 2월 1일,miomiomine,5.0,"주말 저녁 친구들과 가든 커리, 새우 커리, 탄두리\n\n치킨과 플레인, 갈릭, 버..."
2,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143,제주,2020년 11월 2일,seohodong,5.0,후각이 예민해서 양고기를 잘 못먹는편인데\n양갈비 너무 맛있게 잘먹었어요. 특유의 ...
3,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143,제주,2020년 9월 18일,orldtraveler,5.0,너무너무 맛있어요 ㅠㅠㅠ 다음에도 온다면 무조건 재방문 의사 있습니다 꼭꼭 가세요 ...
4,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143,제주,2020년 8월 24일,wlsdlrla,5.0,맛은 물론 분위기까지 좋았어요! 양고기 잡내도 안나고 라씨는 맛있고 버터난까지 알차...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7411,홍요깃거리카페,NaN,NaN,"아시아 요리, 한국",NaN,NaN,NaN,아시아요리 한국,0.0,0.000000,NaN,NaN,NaN,NaN,
7412,갈치공장,NaN,"₩12,000 - ₩30,000","해산물, 아시아 요리, 한국",NaN,NaN,NaN,해산물 아시아요리 한국,0.0,0.000000,NaN,NaN,NaN,NaN,
7413,주르레식당,NaN,NaN,"아시아 요리, 한국, 컨템퍼러리, 퓨전",NaN,NaN,NaN,아시아요리 한국 컨템퍼러리 퓨전,0.0,0.000000,NaN,NaN,NaN,NaN,
7414,빠레뜨 한남 제주협재점,NaN,NaN,NaN,NaN,"점심식사, 저녁식사",NaN,생략,0.0,0.000000,NaN,NaN,NaN,NaN,
7415,Seppy Bagel,NaN,NaN,미국 요리,NaN,NaN,NaN,미국요리,0.0,0.000000,NaN,NaN,NaN,NaN,

In [27]:
from sklearn.feature_extraction.text import CountVectorizer  # 피체 벡터화
from sklearn.metrics.pairwise import cosine_similarity  # 코사인 유사도

count_vect_category = CountVectorizer(min_df=0, ngram_range=(1,2))
place_category = count_vect_category.fit_transform(total['cate_mix'])
place_simi_cate = cosine_similarity(place_category, place_category)
place_simi_cate_sorted_ind = place_simi_cate.argsort()[:, ::-1]

In [36]:
import numpy as np

# 리뷰 텍스트 데이터 간의 텍스트 피쳐 벡터라이징
count_vect_review = CountVectorizer(min_df=2, ngram_range=(1,2))
place_review = count_vect_review.fit_transform(total['review_text']) 

# 리뷰 텍스트 간의 코사인 유사도 따지기
place_simi_review = cosine_similarity(place_review, place_review)
place_simi_review_sorted_ind = place_simi_review.argsort()[:, ::-1]

place_simi_co = (
                 + place_simi_cate * 0.3 # 공식 1. 카테고리 유사도
                 + place_simi_review * 1 # 공식 2. 리뷰 텍스트 유사도
                 + np.repeat([total['review_count'].values], len(total['review_count']) , axis=0) * 0.001  # 공식 3. 블로그 리뷰가 얼마나 많이 올라왔는지
                 + np.repeat([total['review_mean'].values], len(total['review_mean']) , axis=0) * 0.005     # 공식 4. 블로그 별점이 얼마나 높은지
                 )

place_simi_co_sorted_ind = place_simi_co.argsort()[:, ::-1] 

def find_simi_place(df, sorted_ind, place_name, top_n):
    place_title = df[df['장소이름'] == place_name]
    place_index = place_title.index.values
    similar_indexes = sorted_ind[place_index, :(top_n)]
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]

find_simi_place(df, place_simi_co_sorted_ind, '인디언키친', 5)

,장소이름,소개,가격대,요리,특별식 제공,식사 시간,특징,cate_mix,review_count,review_mean
0,인디언키친,제주도 인도음심점,"₩15,000 - ₩30,000","인도 요리, 아시아 요리, 건강식","채식주의 식단, 채식 옵션, 할랄, 코셔, 글루텐 프리","점심식사, 저녁식사, 음료","테이크아웃, 예약, 야외석, 좌석, 주차 가능, 무료 주차장, 유아용 의자 있음, ...",인도요리 아시아요리 건강식,70.0,4.757143
24,리치망고,NaN,NaN,NaN,NaN,NaN,테이크아웃,생략,65.0,4.138462
29,곰막,NaN,NaN,NaN,NaN,NaN,NaN,생략,34.0,4.382353
67,칠돈가,NaN,NaN,NaN,NaN,NaN,NaN,생략,32.0,4.312500
39,바당봉봉,NaN,NaN,NaN,NaN,NaN,테이크아웃,생략,19.0,4.578947

In [8]:
review_df = pd.read_csv('C:/Users/dwshi/Downloads/ta_reviews_jeju_final.csv')
review_df

,region,title,review_date,review_id,review_rate,review_text
0,제주,인디언키친,리뷰 게시 날짜: 3주 전,Go784818,1,전에 여기 너무 좋다고 리뷰 올렸고 그래서 친구 부부와 같이 다시 찾았습니다. 저희...
1,제주,인디언키친,2021년 2월 1일,miomiomine,5,"주말 저녁 친구들과 가든 커리, 새우 커리, 탄두리\n\n치킨과 플레인, 갈릭, 버..."
2,제주,인디언키친,2020년 11월 2일,seohodong,5,후각이 예민해서 양고기를 잘 못먹는편인데\n양갈비 너무 맛있게 잘먹었어요. 특유의 ...
3,제주,인디언키친,2020년 9월 18일,orldtraveler,5,너무너무 맛있어요 ㅠㅠㅠ 다음에도 온다면 무조건 재방문 의사 있습니다 꼭꼭 가세요 ...
4,제주,인디언키친,2020년 8월 24일,wlsdlrla,5,맛은 물론 분위기까지 좋았어요! 양고기 잡내도 안나고 라씨는 맛있고 버터난까지 알차...
...,...,...,...,...,...,...
6166,제주,용출횟집,2017년 8월 24일,DJMinSEOUL,1,성인 5 + 아기 1명은 갔더니 4명짜리 테이블로 안내하며 아기는 낑겨 앉고 성인 ...
6167,제주,용출횟집,2016년 5월 13일,SeungchulShin,4,제주도 북부쪽에 위치한 횟집입니다. 식당앞에서 비행기들이 제주공항에 착륙하기 위해서...
6168,제주,용출횟집,2015년 12월 18일,Hye Jin L,5,용담 해안도로를 따라 횟집들이 쭉 늘어서 있으나 그 중 유난히 회가 쫄깃쫄깃하고 감...
6169,제주,요레,2017년 9월 29일,Navigator683575,5,여러가지 다양한 퓨전요리라 입맛에 맞는\n요리를 선택해서 먹을수있어 좋아요~^^\n...
6170,제주,요레,2019년 1월 16일,NiharikaK74,3,서버는 고객을 대하는 방법을 정확히 알고있었습니다. . 정말 아름답게 꾸며진 곳. ...

In [62]:
def to_list(arr):
    ml = arr.replace(' ','').split("'")
    if '[' in ml:
        ml.remove('[')
    if ']' in ml:
        ml.remove(']')
    while ',' in ml:
        ml.remove(',')
    string = ''
    for i in ml:
        string = string+' '+i
    return string

df = pd.read_excel('./크롤링 데이터/수정된파일.xlsx')
df.drop('Column1', axis=1, inplace=True)
df = df[df['타입'] == '음식점']

df['cate_mix'] = df.apply(lambda val:to_list(val.해시태그), axis=1)
df.set_index('장소', inplace=True)
df.reset_index(inplace=True)
df

,장소,타입,위치,해시태그,좋아요,찜하기,리뷰,일정 등록,방문했어요,조회,...,유아 서비스 상세,부대시설 기타,Late체크인여부,공항교통편,장애인전용객실여부,유아 서비스 기타,취급품목,취급품목 기타,택배배송여부,cate_mix
0,휴림,음식점,제주특별자치도 제주시 애월읍 광령남서길 40,"['부모 ', '친구 ', '아이', '커플 ', '액티비티 ', '야영장 ', '...",0,3,0,0,0,8566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,부모 친구 아이 커플 액티비티 야영장 캠핑장
1,봄날카페,음식점,제주특별자치도 제주시 애월읍 애월로1길 25,"['카페 ', '커피 ', '음료']",43,558,141,0,2,56839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페 커피 음료
2,명진전복,음식점,제주특별자치도 제주시 구좌읍 해맞이해안로 1282,"['전복 ', '돌솥밥 ', '회']",27,537,66,0,0,43587,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,전복 돌솥밥 회
3,몽상드애월(몽상),음식점,제주특별자치도 제주시 애월읍 애월북서길 56-1,"['카페 ', '커피 ', '음료', '디저트']",18,421,66,0,1,39458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페 커피 음료 디저트
4,서연의집(영화 건축학개론),음식점,제주특별자치도 서귀포시 남원읍 위미해안로 86,"['카페 ', '커피 ', '아메리카노']",14,218,66,0,1,34936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페 커피 아메리카노
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331,황금어장(제주시),음식점,제주특별자치도 제주시 사장길 14,"['향토음식 ', '옥돔미역국 ', '갈치호박국', '성게국 ', '방어회']",1,7,0,0,0,4289,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,향토음식 옥돔미역국 갈치호박국 성게국 방어회
1332,황원갈비,음식점,제주특별자치도 제주시 구좌읍 김녕로 129,"['갈비 ', '막창구이 ', '갈비탕', '육개장']",1,3,0,0,0,850,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,갈비 막창구이 갈비탕 육개장
1333,후년하우스,음식점,제주특별자치도 제주시 삼봉로 12,"['소고기샤브샤브 ', '돼지고기샤브샤브 ', '오리고기샤브샤브', '말고기샤브샤브...",0,10,0,0,0,1157,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,소고기샤브샤브 돼지고기샤브샤브 오리고기샤브샤브 말고기샤브샤브 샤브샤브
1334,흑돼지돈까스 뷔페 밀라네사,음식점,제주특별자치도 제주시 매촌2길 78 (도련1동) 어베인건물 1층,"['흑돼지 ', '돈까스 ', '뷔페', '흑돼지돈까스 ', '키즈존 ', '놀이방']",1,1,0,0,0,1342,...,수유실,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,흑돼지 돈까스 뷔페 흑돼지돈까스 키즈존 놀이방
1335,흑염소마루,음식점,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,"['흑염소탕 ', '육회 ', '전골', '수육']",0,0,0,0,0,1487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,흑염소탕 육회 전골 수육

In [65]:
from sklearn.feature_extraction.text import CountVectorizer  # 피체 벡터화
from sklearn.metrics.pairwise import cosine_similarity  # 코사인 유사도

count_vect_category = CountVectorizer(min_df=0, ngram_range=(1,2))
place_category = count_vect_category.fit_transform(df['cate_mix'])
place_simi_cate = cosine_similarity(place_category, place_category)
place_simi_cate_sorted_ind = place_simi_cate.argsort()[:, ::-1]

def find_simi_place(df, sorted_ind, place_name, top_n):
    place_title = df[df['장소'] == place_name]
    place_index = place_title.index.values
    similar_indexes = sorted_ind[place_index, :(top_n)]
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]

find_simi_place(df, place_simi_cate_sorted_ind, '휴림', 6)[1:]

,장소,타입,위치,해시태그,좋아요,찜하기,리뷰,일정 등록,방문했어요,조회,...,유아 서비스 상세,부대시설 기타,Late체크인여부,공항교통편,장애인전용객실여부,유아 서비스 기타,취급품목,취급품목 기타,택배배송여부,cate_mix
984,성화정,음식점,제주특별자치도 서귀포시 안덕면 신화역사로304번길 38,"['부모 ', '커플 ', '친구', '아이 ', '휴식/힐링']",0,0,0,0,0,526,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,부모 커플 친구 아이 휴식/힐링
374,중식당 청,음식점,제주특별자치도 제주시 노연로 80 메종글래드 제주,"['부모 ', '커플 ', '혼자', '친구 ', '아이 ', '중식']",2,1,2,0,2,685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,부모 커플 혼자 친구 아이 중식
1159,제주돌창고,음식점,제주특별자치도 제주시 한경면 조수7길 8,"['휴식/힐링 ', '부모 ', '커플', '친구 ', '아이']",1,5,0,0,0,1141,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,휴식/힐링 부모 커플 친구 아이
786,델리,음식점,제주특별자치도 제주시 노연로 12,"['부모 ', '커플 ', '친구', '아이 ', '휴식/힐링']",0,0,0,0,0,205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,부모 커플 친구 아이 휴식/힐링
1033,써니사이드비치,음식점,제주특별자치도 서귀포시 남원읍 태신해안로 129 (태흥리),"['부모 ', '커플 ', '친구', '아이 ', '펜션 ', '일출 ', '일몰']",0,0,0,0,0,540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,부모 커플 친구 아이 펜션 일출 일몰

In [68]:
df2 = pd.read_csv('./크롤링 데이터/category_data.csv')
df2.drop('Unnamed: 0', axis=1, inplace=True)
df2

          name main_category sub_category
0      한라산국립공원            자연            산
1          송악산            자연            산
2          산방산            자연            산
3          백록담            자연            산
4     한라산어리목코스            자연            산
...        ...           ...          ...
3391      풍년상회            쇼핑        상점·상가
3392    프레쉬모먼트            쇼핑        상점·상가
3393    피크닉메이트            쇼핑        상점·상가
3394      한라꽃방            쇼핑        상점·상가
3395       한복담            쇼핑        상점·상가

[3396 rows x 3 columns]

In [114]:
df3 = pd.merge(df, df2, how='inner', left_on='장소', right_on='name')
df3.drop(['cate_mix','name','sub_category'], axis=1, inplace=True)
df3

,장소,타입,위치,해시태그,좋아요,찜하기,리뷰,일정 등록,방문했어요,조회,...,유아 서비스 상세,부대시설 기타,Late체크인여부,공항교통편,장애인전용객실여부,유아 서비스 기타,취급품목,취급품목 기타,택배배송여부,main_category
0,휴림,음식점,제주특별자치도 제주시 애월읍 광령남서길 40,"['부모 ', '친구 ', '아이', '커플 ', '액티비티 ', '야영장 ', '...",0,3,0,0,0,8566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,자연
1,휴림,음식점,제주특별자치도 제주시 애월읍 광령남서길 40,"['부모 ', '친구 ', '아이', '커플 ', '액티비티 ', '야영장 ', '...",0,3,0,0,0,8566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,레저/체험
2,봄날카페,음식점,제주특별자치도 제주시 애월읍 애월로1길 25,"['카페 ', '커피 ', '음료']",43,558,141,0,2,56839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페
3,명진전복,음식점,제주특별자치도 제주시 구좌읍 해맞이해안로 1282,"['전복 ', '돌솥밥 ', '회']",27,537,66,0,0,43587,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
4,몽상드애월(몽상),음식점,제주특별자치도 제주시 애월읍 애월북서길 56-1,"['카페 ', '커피 ', '음료', '디저트']",18,421,66,0,1,39458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1351,황금어장(제주시),음식점,제주특별자치도 제주시 사장길 14,"['향토음식 ', '옥돔미역국 ', '갈치호박국', '성게국 ', '방어회']",1,7,0,0,0,4289,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,향토음식
1352,황원갈비,음식점,제주특별자치도 제주시 구좌읍 김녕로 129,"['갈비 ', '막창구이 ', '갈비탕', '육개장']",1,3,0,0,0,850,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
1353,후년하우스,음식점,제주특별자치도 제주시 삼봉로 12,"['소고기샤브샤브 ', '돼지고기샤브샤브 ', '오리고기샤브샤브', '말고기샤브샤브...",0,10,0,0,0,1157,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
1354,흑돼지돈까스 뷔페 밀라네사,음식점,제주특별자치도 제주시 매촌2길 78 (도련1동) 어베인건물 1층,"['흑돼지 ', '돈까스 ', '뷔페', '흑돼지돈까스 ', '키즈존 ', '놀이방']",1,1,0,0,0,1342,...,수유실,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,양식
1355,흑염소마루,음식점,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,"['흑염소탕 ', '육회 ', '전골', '수육']",0,0,0,0,0,1487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식

In [115]:
def apply(string):
    arr = ['향토음식','한식','양식','일식','중식','동남아식','카페']
    if string in arr:
        return 0
    else:
        return 1
df3['if_in'] = df3.apply(lambda val:apply(val.main_category), axis=1)
df3 = df3[df3['if_in'] == 0]
df3.drop('if_in', axis=1, inplace=True)
df3.set_index('장소',inplace=True)
df3

C:\Users\dwshi\anaconda3\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,타입,위치,해시태그,좋아요,찜하기,리뷰,일정 등록,방문했어요,조회,SNS 공유,...,유아 서비스 상세,부대시설 기타,Late체크인여부,공항교통편,장애인전용객실여부,유아 서비스 기타,취급품목,취급품목 기타,택배배송여부,main_category
장소,,,,,,,,,,,,,,,,,,,,,
봄날카페,음식점,제주특별자치도 제주시 애월읍 애월로1길 25,"['카페 ', '커피 ', '음료']",43,558,141,0,2,56839,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페
명진전복,음식점,제주특별자치도 제주시 구좌읍 해맞이해안로 1282,"['전복 ', '돌솥밥 ', '회']",27,537,66,0,0,43587,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
몽상드애월(몽상),음식점,제주특별자치도 제주시 애월읍 애월북서길 56-1,"['카페 ', '커피 ', '음료', '디저트']",18,421,66,0,1,39458,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페
서연의집(영화 건축학개론),음식점,제주특별자치도 서귀포시 남원읍 위미해안로 86,"['카페 ', '커피 ', '아메리카노']",14,218,66,0,1,34936,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,카페
제주김만복(만복이네김밥집),음식점,제주특별자치도 제주시 오라로 41,"['전복김밥 ', '통전복주먹밥 ', '미역국']",62,1007,60,0,1,67251,89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
황금어장(제주시),음식점,제주특별자치도 제주시 사장길 14,"['향토음식 ', '옥돔미역국 ', '갈치호박국', '성게국 ', '방어회']",1,7,0,0,0,4289,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,향토음식
황원갈비,음식점,제주특별자치도 제주시 구좌읍 김녕로 129,"['갈비 ', '막창구이 ', '갈비탕', '육개장']",1,3,0,0,0,850,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
후년하우스,음식점,제주특별자치도 제주시 삼봉로 12,"['소고기샤브샤브 ', '돼지고기샤브샤브 ', '오리고기샤브샤브', '말고기샤브샤브...",0,10,0,0,0,1157,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식
흑돼지돈까스 뷔페 밀라네사,음식점,제주특별자치도 제주시 매촌2길 78 (도련1동) 어베인건물 1층,"['흑돼지 ', '돈까스 ', '뷔페', '흑돼지돈까스 ', '키즈존 ', '놀이방']",1,1,0,0,0,1342,1,...,수유실,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,양식
흑염소마루,음식점,제주특별자치도 서귀포시 남원읍 태위로663번길 1-1,"['흑염소탕 ', '육회 ', '전골', '수육']",0,0,0,0,0,1487,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,한식

In [116]:
df3.to_csv('com_cook.csv', encoding='utf-8')